name: python_github_tutorial
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - pytest
  - pip
  - mock
  - ipython 
  - nbconvert 
  - jupyter 
  - pygments
  - numpydoc
  - sphinx=6.1.1
  - sphinx_rtd_theme
  - nbsphinx
  - sphinxcontrib
  - pip:
    - sphinxcontrib-svg2pdfconverter
    - sphinxcontrib-video
    - sphinxcontrib-serializinghtml
